### ISSUE TITLE
$(LIB) spacing

### ISSUE THREAD

**Issue by brendankirkpatrick** [mirai-computing/cbp2make#6]
When generating the Makefile, the spacing on LinkerLibraries is incorrect for the line LIB_DEBUG, i.e.
![image](https://github.com/mirai-computing/cbp2make/assets/99195024/53e88fd9-6e85-48eb-a5db-5edd19e605d5)

When running make, output is missing a space between paths. Looks like this:
![image](https://github.com/mirai-computing/cbp2make/assets/99195024/19194190-b5c7-4d04-b4f1-36001a64cf8a)

Proposed solution: 
Add a space to the end of the last path in the loop in cbproject.cpp at line 834. 
```
for (int i = 0; i < m_LinkerLibraries.GetCount(); i++)
   {
    CString lib_pathname = m_LinkerLibraries[i];
    CString lib_path, lib_name, lib_ext;
    SplitFilePathName(lib_pathname, lib_path, lib_name, lib_ext);
    //CString lib_name = m_LinkerLibraries[i];
    //CString lib_ext = ExtractFileExt(lib_name);
    //if (lib_ext.IsEmpty())
    if (lib_path.IsEmpty())
    {
     if (pl->IsLibraryExtension(lib_ext))
     {
      CString lib_base_name = pl->BaseLibraryName(lib_name,lib_ext);
      line = JoinStr(line,tc->LinkLibrarySwitch()+pl->ProtectPath(pl->Pd(lib_base_name),Config.QuotePathMode()),' ');
      //line.Append(" ");
     }
     else
     {
      line = JoinStr(line,tc->LinkLibrarySwitch()+pl->ProtectPath(pl->Pd(lib_name),Config.QuotePathMode()),' ');
      //line.Append(" ");
     }
    }
    else
    {
     line = JoinStr(line,pl->ProtectPath(pl->Pd(lib_pathname),Config.QuotePathMode()),' ');
     // line.Append(" ");
    }
```

**Comment by mirai-computing** [comment]
Hi, there! You've caught a dinosaur age bug by the looks of it :) However, the real culprit here is not this loop at line 834, but a later call that joins project and target options at line 893 which looks like this:
`m_Makefile.AddMacro(target->Name(STR_LIB+"_",Config.MacroVariableCase()), CGlobalVariable::Convert("$("+STR_LIB+tc_suffix+")"+pl->Pd(target->Libs(*pl,tc->LinkLibrarySwitch())),Config.MacroVariableCase()),section);  
`
All other macros are made by calling target->something() that eventually invokes CBuildTarget::MakeOptions() that correctly connects both parts, but this one is different for some reason. For a fixed library order (project,target) there's an obvious and simple fix: just add a space after closing bracket in `"$("+STR_LIB+tc_suffix+") <space> "`. For a variable library order, some changes has to be made to CBuildTarget::Libs() to make it behave just like all other similar functions. C::B has an option for linker options order and it probably should be applied to library link order too, but this is not how it's implemented in cbp2make. Well, yes, this definitely requires some changes.

**Comment by mirai-computing** [comment]
OK, fixed that, now LIBS macro also respects linker options order and required spacing is there.
